// <auto-generated />
using System;
using FloraBack.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FloraBack.DataAccess.Migrations.Product
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FloraBack.Domains.Entities.Product.ProductData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FloraBack.Domains.Entities.Product.ProductImgData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("FloraBack.Domains.Entities.Product.ProductData", b =>
                {
                    b.OwnsOne("FloraBack.Domains.Entities.Product.CategoryData", "Category", b1 =>
                        {
                            b1.Property<int>("ProductDataId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("Name")
                                .HasColumnType("int");

                            b1.HasKey("ProductDataId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductDataId");
                        });

                    b.OwnsOne("FloraBack.Domains.Entities.Product.ProductDescriptionData", "Description", b1 =>
                        {
                            b1.Property<int>("ProductDataId")
                                .HasColumnType("int");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.HasKey("ProductDataId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductDataId");

                            b1.OwnsOne("FloraBack.Domains.Entities.Product.DescriptionAdvanced", "DescriptionAdvanced", b2 =>
                                {
                                    b2.Property<int>("ProductDescriptionDataProductDataId")
                                        .HasColumnType("int");

                                    b2.Property<int>("H")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .HasColumnType("int");

                                    b2.Property<int>("L")
                                        .HasColumnType("int");

                                    b2.Property<int>("W")
                                        .HasColumnType("int");

                                    b2.HasKey("ProductDescriptionDataProductDataId");

                                    b2.ToTable("Products");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductDescriptionDataProductDataId");
                                });

                            b1.Navigation("DescriptionAdvanced")
                                .IsRequired();
                        });

                    b.Navigation("Category")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("FloraBack.Domains.Entities.Product.ProductImgData", b =>
                {
                    b.HasOne("FloraBack.Domains.Entities.Product.ProductData", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FloraBack.Domains.Entities.Product.ProductData", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
